apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: platform
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.15.2
    helm:
      valuesObject:
        provider:
          name: aws
        policy: sync
        domainFilters:
          - swiftwad.com
        txtOwnerId: swiftwad-staging
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::905418331655:role/external-dns-swiftwad-staging
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
