apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: external-dns-cloudflare
    creationPolicy: Owner
  data:
    - secretKey: apiToken
      remoteRef:
        key: platform/cloudflare-dns
        property: apiToken
