apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api-staging
  namespace: argocd
spec:
  project: vendor-acme
  sources:
    - repoURL: https://github.com/juwondre/swiftwad-gitops
      targetRevision: main
      path: charts/app-template
      helm:
        valueFiles:
          - $values/envs/staging/sample-api.yaml
    - repoURL: https://github.com/juwondre/swiftwad-gitops
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: sample-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
